import { Urbanist,Figtree,Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/ shared/header/Header";

const urbanist = Urbanist({
  weight:["600", "500"],
  variable:"--font-urbanist",
});

const  figtree = Figtree({
  weight :["700",],
  variable:"--font-figtree"
});

const poppins = Poppins({
  weight:["400"],
  variable:"--font-poppins",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={" antialiased max-w-[1920px] max-h-[964px] overflow-hidden"}
      >
        {/* applicationHeader */}
        <Header />
        {children}
      </body>
    </html>
  );
}
