import {
  Urbanist,
  Figtree,
  Poppins,
  Inter,
  Outfit,
  Hind,
  Cabin,
} from "next/font/google";
import "./globals.css";
import Header from "./components/ shared/header/Header";
import Footer from "./components/reusable/footer/Footer";

const urbanist = Urbanist({
  weight: ["600", "500","400"],
  variable: "--font-urbanist",
});

const figtree = Figtree({
  weight: ["700"],
  variable: "--font-figtree",
});

const poppins = Poppins({
  weight: ["400"],
  variable: "--font-poppins",
});

const inter = Inter({
  weight: ["500"],
  variable: "--font-inter",
});

const outfit = Outfit({
  weight: ["400"],
  variable: "--font-outfit",
});

const cabin = Cabin({
  weight: ["400", "700"],
  variable: "--font-cabin",
});

const hindVadodara = Hind({
  weight: ["400"],
  variable: "--font-hind",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cabin.variable} ${hindVadodara.variable} ${outfit.variable} ${urbanist.variable} ${figtree.variable} ${poppins.variable} ${inter.variable}
        antialiased w-full min-h-screen overflow-x-hidden`}
      >
        {/* applicationHeader */}
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
